name: "build"
# on:
#  pull_request:
#  push:
jobs:
  defaults:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    uses: cachix/install-nix-action@v7
  ghc-865:
    name: GHC 8.6.5
    steps:
    - name: GHC 8.6.5
      uses: cachix/cachix-action@v5
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        attributes: "hie.ghc-865"
