name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build (GHC 8.6.5)
      run: nix build -f . hie.ghc-865 --out-link hie-ghc-865
    - name: GC
      run: nix-collect-garbage -d
    - name: Build (GHC 8.8.2)
      run: nix build -f . hie.ghc-882 --out-link hie-ghc-882
    - name: GC
      run: nix-collect-garbage -d
    - name: Build (GHC 8.8.3)
      run: nix build -f . hie.ghc-883 --out-link hie-ghc-883
