name: "Build"

on:
  pull_request:
  push:

jobs:
  ghc-865:
    name: GHC 8.6.5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -f . hie.ghc-865 -L
  ghc-882:
    name: GHC 8.8.2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -f . hie.ghc-882 -L
  ghc-883:
    name: GHC 8.8.3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -f . hie.ghc-883 -L
  ghc-884:
    name: GHC 8.8.4
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -f . hie.ghc-884 -L
  compose:
    name: Compose
    runs-on: ubuntu-latest
    needs:
    - ghc-865
    - ghc-882
    - ghc-883
    - ghc-884
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -f . composed -L
