name: "build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    uses:
    - actions/checkout@v2
    - cachix/install-nix-action@v7
    steps:
    - name: GHC 8.6.5
      uses: cachix/cachix-action@v5
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        attributes: "hie.ghc-865"
    - name: GHC 8.8.2
      uses: cachix/cachix-action@v5
      with:
        name: nix-hie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        attributes: "hie.ghc-882"
